### ISSUE TITLE
Data team peer review 7/25-7/29

### ISSUE THREAD

**Issue by karitotp** [mapbox/mapping#216] opened 2016-08-02 22:10 UTC
Last peer review ticket: [#214](https://github.com/mapbox/mapping/issues/214)

#### Mapping projects to be reviewed:

1. [To-Fix](http://osmlab.github.io/to-fix/)
2. [Turn restriction in Canada](https://github.com/mapbox/mapping/issues/213)

#### Instructions
* Download `.osm` files for last week.
 - [2016/07/25 - 2016/07/29](https://s3.amazonaws.com/mapbox/osm-history-processor/day/latest.osm.tar.gz)

* Extract the tar file and select any OSM file of the team member.
* Each team member will have an .osm file of edits for the last seven days. For example: `latest-andygol.osm`. Select any `.osm` file and open the data in JOSM. 
* If you don't find any osm file of a particular team member, then it means that user has not edited during the week.
* Examine user edits in detail. In JOSM, select a random small area edited by the user and press `3` to zoom.
* Download the latest data in OSM as a new layer and add a filter `Cmd + F` to see only the user's edits, e.g. `user:andygol`.

![andyfilter3](https://cloud.githubusercontent.com/assets/6770741/14813545/cf7409d2-0bbf-11e6-9389-5b6132b7bb55.gif)

* Select a way/node and load the the history (`Ctrl + H`), the changeset comment will describe what specific project the user was working on.
* To get an OSM link to the object, click `Cmd + Shift + H`. 
* Note down any feedback for each user in this ticket or comment directly in the changeset. Use this format:

```
username
changeset link - issue to fix
```

* @krishnanammala @chtnha or @karitotp will post the feedback in the ticket (Use Github handle because OSM name is different from Github name) and make necessary changes on the same day.
* Close the ticket once user's have fixed their edits.

For clarifications, discuss with the @mapbox/team-data in this ticket.

**Comment by karitotp** [comment] 2016-08-03 19:31
@ridixcr 

#### Split ways
https://www.openstreetmap.org/way/431622201/history
https://www.openstreetmap.org/node/4320170256/history
https://www.openstreetmap.org/way/132510710/history

#### No satellite imagery view
https://www.openstreetmap.org/way/412759338/history
https://www.openstreetmap.org/way/246056070/history

#### Missing crossing ways
https://www.openstreetmap.org/node/352735558/history

#### Improve this way
https://www.openstreetmap.org/way/434265798/history
https://www.openstreetmap.org/way/426561333/history
https://www.openstreetmap.org/way/431811517/history

#### Fix number of lanes 
https://www.openstreetmap.org/way/353015896/history
https://www.openstreetmap.org/way/435373690/history
https://www.openstreetmap.org/way/353015900/history
https://www.openstreetmap.org/way/435373691/history and add missing turn lanes  , 2 ways 

#### Split the way and fix turn lanes 
https://www.openstreetmap.org/way/435373688/history

#### Missing turn lanes 
https://www.openstreetmap.org/node/237914511/history
https://www.openstreetmap.org/way/22078044/history
https://www.openstreetmap.org/way/22099097/history along way
https://www.openstreetmap.org/way/420884736/history  // turn lanes ||right
https://www.openstreetmap.org/way/435367619/history
https://www.openstreetmap.org/way/244501324/history
https://www.openstreetmap.org/way/435368595/history

#### Incorrect end of turn lane
https://www.openstreetmap.org/way/240337216/history

**Comment by karitotp** [comment] 2016-08-03 19:32
@poornibadrinath 

#### Incorrect name of highway , the layer TIGER says other name
https://www.openstreetmap.org/way/18162230/history

#### Improve this highway
https://www.openstreetmap.org/way/435093026/history

**Comment by karitotp** [comment] 2016-08-03 19:33
@maning 

#### Improve this building, incorrect shape
https://www.openstreetmap.org/way/429199900/history
https://www.openstreetmap.org/way/427288208/history
https://www.openstreetmap.org/way/317462859/history
https://www.openstreetmap.org/way/426857623/history
https://www.openstreetmap.org/way/427147375/history
https://www.openstreetmap.org/way/429204953/history
https://www.openstreetmap.org/way/429382330/history
https://www.openstreetmap.org/way/429569036/history

#### Crossing buildings
https://www.openstreetmap.org/way/121783265/history

#### Orthogonalize this building
https://www.openstreetmap.org/way/429332718/history
https://www.openstreetmap.org/way/427275212/history

**Comment by karitotp** [comment] 2016-08-03 19:33
@oini 
#### Untagged way
https://www.openstreetmap.org/way/434315898

#### Improve the aligning of the highway
https://www.openstreetmap.org/way/6775551 - check around
https://www.openstreetmap.org/way/434315939

**Comment by karitotp** [comment] 2016-08-03 19:34
@chtnha 
#### Improve the aligning of the highway
https://www.openstreetmap.org/way/260744199
https://www.openstreetmap.org/way/119160256
https://www.openstreetmap.org/way/407790740
https://www.openstreetmap.org/way/22829821
https://www.openstreetmap.org/way/260819519

#### Add bridge
https://www.openstreetmap.org/node/1175774443

#### Crossing waterway with highway
https://www.openstreetmap.org/way/433808597

**Comment by karitotp** [comment] 2016-08-03 19:35
@dannykath 
#### Fix `turn:lanes:forward` - number of lanes &/or signal
https://www.openstreetmap.org/way/435347967
https://www.openstreetmap.org/way/435396177
https://www.openstreetmap.org/way/435361422
https://www.openstreetmap.org/way/435382529
https://www.openstreetmap.org/way/435324252
https://www.openstreetmap.org/way/435382529

#### Fix `turn:lanes:backward` - number of lanes &/or signal
https://www.openstreetmap.org/way/435329653
https://www.openstreetmap.org/way/435367421
https://www.openstreetmap.org/way/435373676
https://www.openstreetmap.org/way/435365885

#### Missing `turn:lanes:backward` 
https://www.openstreetmap.org/way/435333516
https://www.openstreetmap.org/way/435367686

#### You should add a dual carriageway
https://www.openstreetmap.org/way/435380558

#### Incorrect starting of the turn lanes
https://www.openstreetmap.org/changeset/41195264

**Comment by karitotp** [comment] 2016-08-03 19:36
@maanyaumashaanker 

#### Add missing turn lanes
https://www.openstreetmap.org/way/110570257
https://www.openstreetmap.org/way/85686787
https://www.openstreetmap.org/way/24073538
https://www.openstreetmap.org/way/24078174
https://www.openstreetmap.org/way/433773220
https://www.openstreetmap.org/way/97011626

#### Incorrect starting of the turn lanes
https://www.openstreetmap.org/way/435091067
https://www.openstreetmap.org/way/435091068
https://www.openstreetmap.org/way/435091070 and incorrect number of lanes in forward
https://www.openstreetmap.org/way/433773222

#### Incorrect number of lanes
https://www.openstreetmap.org/way/435091072 in forward
https://www.openstreetmap.org/way/433773221 in forward and backward

**Comment by karitotp** [comment] 2016-08-03 19:37
@pratikyadav 
#### Line does not match the bing aerial imagery
https://www.openstreetmap.org/way/150850618

#### Add name of road using New & Misaligned TIGER Roads (2015)
https://www.openstreetmap.org/way/434312883

#### Add multipolygon
https://www.openstreetmap.org/way/435091342

#### Improve the aligning of the water
https://www.openstreetmap.org/way/368435592

**Comment by karitotp** [comment] 2016-08-03 19:37
@ediyes 
#### Add bridge on this road
https://www.openstreetmap.org/way/48181094/history

#### Improve the end of this street based on  imagery
https://www.openstreetmap.org/way/21629407/history

#### Fix self intersecting  highways
https://www.openstreetmap.org/way/435401065/history

**Comment by karitotp** [comment] 2016-08-03 19:38
@nikhilprabhakar 
#### Remove turn lanes  unnecessary
https://www.openstreetmap.org/way/312343576
https://www.openstreetmap.org/way/312343574

#### Way untagged
https://www.openstreetmap.org/way/435022637

**Comment by karitotp** [comment] 2016-08-03 19:40
@piligab 
#### Wrong starting turn lanes
https://www.openstreetmap.org/way/435382960

#### Missing turn lanes both way
https://www.openstreetmap.org/way/435382958 

#### Wrong tagging turn lane - review diferents satelite image
https://www.openstreetmap.org/way/435382985
https://www.openstreetmap.org/way/202375197

#### Missing turn lanes along way
https://www.openstreetmap.org/way/186590712
https://www.openstreetmap.org/way/333529427
https://www.openstreetmap.org/way/58744580
https://www.openstreetmap.org/way/31296852
https://www.openstreetmap.org/way/232302217
https://www.openstreetmap.org/way/285375465
https://www.openstreetmap.org/way/231305597

#### Remove way unnecessary and add turn lanes in main street  - not exist physical separation
https://www.openstreetmap.org/way/324125961

#### Split ways and add turn lanes - exist physical separation
https://www.openstreetmap.org/way/31296917
https://www.openstreetmap.org/way/435367460

#### Wrong number lanes turn lanes
https://www.openstreetmap.org/way/435393433
https://www.openstreetmap.org/way/31233108

#### Remove turn lanes
https://www.openstreetmap.org/way/314063789

**Comment by karitotp** [comment] 2016-08-03 19:40
@samely 

#### Combine the bridges
https://www.openstreetmap.org/way/105851792/history

#### Doesn't work if satellite imagery isn't clear
https://www.openstreetmap.org/way/357841615/history

#### Incorrect starting or ending of the tunnel
https://www.openstreetmap.org/way/229925642/history

**Comment by karitotp** [comment] 2016-08-03 19:41
@RichRico 
#### Duplicated ways 
 https://www.openstreetmap.org/way/435386992/history
 https://www.openstreetmap.org/way/435387003/history
 https://www.openstreetmap.org/way/435387000/history
 https://www.openstreetmap.org/way/435386997/history
 https://www.openstreetmap.org/way/435387006/history
 https://www.openstreetmap.org/way/435386994/history
 https://www.openstreetmap.org/way/435396506/history
 https://www.openstreetmap.org/way/435387034/history
 https://www.openstreetmap.org/way/435387015/history
 https://www.openstreetmap.org/way/435387024/history
 https://www.openstreetmap.org/way/435396501/history
 https://www.openstreetmap.org/way/435387022/history
 https://www.openstreetmap.org/way/435387030/history
 https://www.openstreetmap.org/way/435387009/history
 https://www.openstreetmap.org/way/435387019/history

**Comment by karitotp** [comment] 2016-08-03 19:41
@jothirnadh 
#### Give form to the road
https://www.openstreetmap.org/way/21454912

**Comment by karitotp** [comment] 2016-08-03 19:42
@planemad 
#### Crossing Highway
https://www.openstreetmap.org/way/434887973
https://www.openstreetmap.org/way/434887975
https://www.openstreetmap.org/way/434887977
https://www.openstreetmap.org/way/427100911
https://www.openstreetmap.org/way/374407210

#### Need to add `layer=1`
https://www.openstreetmap.org/way/427282410
https://www.openstreetmap.org/way/93059072

#### Remove the label `building=yes`
https://www.openstreetmap.org/way/427282410

#### Crossing highway/waterway
https://www.openstreetmap.org/way/236169515
https://www.openstreetmap.org/way/434319091

#### Landuse type residential - unclosed way
https://www.openstreetmap.org/way/434917788

#### Need to add bridges in the way
https://www.openstreetmap.org/way/160915825
https://www.openstreetmap.org/way/129773714
https://www.openstreetmap.org/way/129773698
https://www.openstreetmap.org/way/22832896

**Comment by karitotp** [comment] 2016-08-03 19:43
@Yurasi
#### Wrong turn lanes
https://www.openstreetmap.org/way/435322356/history
https://www.openstreetmap.org/way/435322355/history
https://www.openstreetmap.org/way/435322419/history
https://www.openstreetmap.org/way/435322375/history
https://www.openstreetmap.org/way/435379748/history
https://www.openstreetmap.org/way/435386346/history
https://www.openstreetmap.org/way/435385009/history
https://www.openstreetmap.org/way/435340631/history

**Comment by karitotp** [comment] 2016-08-03 19:45
@luiswalter 
#### `oneway=-1` is not recommended
https://www.openstreetmap.org/way/435358376
https://www.openstreetmap.org/way/435345689 and to adjacent
https://www.openstreetmap.org/way/382386717 and to adjacent
https://www.openstreetmap.org/way/109699060
https://www.openstreetmap.org/way/435336150
https://www.openstreetmap.org/way/435336165
https://www.openstreetmap.org/way/435336205
https://www.openstreetmap.org/way/435331876 and to adjacent
https://www.openstreetmap.org/way/435331864
https://www.openstreetmap.org/way/435331868
https://www.openstreetmap.org/way/435331872
https://www.openstreetmap.org/way/435331870
https://www.openstreetmap.org/way/435385338
https://www.openstreetmap.org/way/313309913

#### Incorrect number of turn lanes
https://www.openstreetmap.org/way/435328866
https://www.openstreetmap.org/way/435327212
https://www.openstreetmap.org/way/435346227

#### Wrong turn lanes
https://www.openstreetmap.org/way/435327231
https://www.openstreetmap.org/way/435327812
https://www.openstreetmap.org/way/435394498

#### You need to add signaling of turn lane
https://www.openstreetmap.org/way/435327225

#### The image doesn't show signal turn lane in all way
https://www.openstreetmap.org/way/435336188

**Comment by karitotp** [comment] 2016-08-03 19:45
@karitotp
#### Align highway
https://www.openstreetmap.org/way/434984755

**Comment by ridixcr** [comment] 2016-08-04 00:15
Thanks  for the feedback team!!!

#### Split ways
https://www.openstreetmap.org/changeset/41227016
https://www.openstreetmap.org/changeset/41227023
https://www.openstreetmap.org/changeset/41074869

#### No satellite imagery view
https://www.openstreetmap.org/way/412759338/history
https://www.openstreetmap.org/way/246056070/history

#### Missing crossing ways
https://www.openstreetmap.org/node/352735558/history - not error

#### Improve this way
https://www.openstreetmap.org/changeset/41227083
https://www.openstreetmap.org/changeset/41227110

#### Fix number of lanes 
https://www.openstreetmap.org/changeset/41202271
https://www.openstreetmap.org/changeset/41227142
https://www.openstreetmap.org/changeset/41227156
https://www.openstreetmap.org/changeset/41227224 and add missing turn lanes  , 2 ways 

#### Split the way and fix turn lanes 
https://www.openstreetmap.org/changeset/41227242

#### Missing turn lanes 
in process

#### Incorrect end of turn lane
https://www.openstreetmap.org/changeset/41201371

**Comment by dannykath** [comment] 2016-08-04 00:46
Thanks for your review team!
#### Fix `turn:lanes:forward` - number of lanes &/or signal
https://www.openstreetmap.org/changeset/41227377
https://www.openstreetmap.org/changeset/41227401
https://www.openstreetmap.org/changeset/41227415

#### Fix `turn:lanes:backward` - number of lanes &/or signal
https://www.openstreetmap.org/changeset/41227459
https://www.openstreetmap.org/changeset/41227481
https://www.openstreetmap.org/changeset/41227488

#### Missing `turn:lanes:backward` 
https://www.openstreetmap.org/changeset/41227499

### You should add a dual carriageway
https://www.openstreetmap.org/changeset/41227590

**Comment by chtnha** [comment] 2016-08-04 06:20
Hey @mapbox/peru-office, Thanks for the feedback. Here are my fixes.
#### Aligned the roads ✅ 
*https://www.openstreetmap.org/way/260819519/history
* https://www.openstreetmap.org/way/260744199/history 
* https://www.openstreetmap.org/way/119160256/history
* https://www.openstreetmap.org/way/51105494/history
* https://www.openstreetmap.org/way/22829821/history

#### Add bridge ✅ 
https://www.openstreetmap.org/way/435597254/history 

#### Crossing waterway with highway ✅ 
https://www.openstreetmap.org/way/433808597/history

**Comment by poornibadrinath** [comment] 2016-08-04 06:44
Thank you for the feedback team! 

**Improved this highway**
https://www.openstreetmap.org/way/435093026/history#map=18/41.10391/-73.92534

**Name of the highway**
https://www.openstreetmap.org/way/18162230/history, even though tiger data says it's Poplar street, it's actually Poplar avenue. This change was made based on local knowledge and map feedback, the user had commented saying it was avenue. Confirmed it by another person by adding a note and also reading about the difference between a street and an avenue. Since this road runs north to south, it is technically an avenue.

**Comment by planemad** [comment] 2016-08-04 10:33
@karitotp thank you. Fixes:

> #### Crossing Highway

https://www.openstreetmap.org/changeset/41229474
https://www.openstreetmap.org/changeset/41229657
https://www.openstreetmap.org/changeset/41230012

> #### Need to add `layer=1`

https://www.openstreetmap.org/changeset/41230012
https://www.openstreetmap.org/changeset/41233408

> #### Remove the label `building=yes`

Wontfix, no building label here

> #### Crossing highway/waterway

Wontfix, needs field survey


> #### Landuse type residential - unclosed way

https://www.openstreetmap.org/changeset/41233482

> #### Need to add bridges in the way

https://www.openstreetmap.org/changeset/41233584
https://www.openstreetmap.org/changeset/41233601
https://www.openstreetmap.org/changeset/41233618

**Comment by ediyes** [comment] 2016-08-04 12:39
Thank for the feedback!!

#### Add bridge on this road
https://www.openstreetmap.org/changeset/41236731

#### Improve the end of this street based on  imagery
https://www.openstreetmap.org/way/21629407/history

#### Fix self intersecting  highways
https://www.openstreetmap.org/way/435401065/history - Not an error

**Comment by piligab** [comment] 2016-08-04 14:35
Thank for the feedback!!

#### Wrong starting turn lanes
https://www.openstreetmap.org/changeset/41203009

#### Missing turn lanes both way
https://www.openstreetmap.org/changeset/41238389

#### Wrong tagging turn lane - review diferents satelite image
https://www.openstreetmap.org/changeset/41238455
https://www.openstreetmap.org/changeset/41238529

#### Missing turn lanes along way
https://www.openstreetmap.org/changeset/41238581
https://www.openstreetmap.org/way/333529427 not an error
https://www.openstreetmap.org/way/58744580 not an error
https://www.openstreetmap.org/way/31296852 not an error
https://www.openstreetmap.org/changeset/41239036
https://www.openstreetmap.org/way/285375465 not an error
https://www.openstreetmap.org/way/231305597 not an error

#### Remove way unnecessary and add turn lanes in main street  - not exist physical separation
https://www.openstreetmap.org/changeset/41239234

#### Split ways and add turn lanes - exist physical separation
https://www.openstreetmap.org/changeset/41239300
https://www.openstreetmap.org/changeset/41239342

#### Wrong number lanes turn lanes
https://www.openstreetmap.org/changeset/41239386
https://www.openstreetmap.org/changeset/41239421

#### Remove turn lanes
https://www.openstreetmap.org/changeset/41202003

**Comment by samely** [comment] 2016-08-04 14:43
Thanks for the feedback team!!!

#### Combine the bridges
https://www.openstreetmap.org/changeset/41239612

#### Incorrect starting or ending of the tunnel
https://www.openstreetmap.org/changeset/41239671

**Comment by karitotp** [comment] 2016-08-04 14:50
Thanks for the review team!!
> #### Align highway

- https://www.openstreetmap.org/changeset/41239788

**Comment by RichRico** [comment] 2016-08-04 14:57
Thanks for the feedback team

#### Duplicated ways 
https://www.openstreetmap.org/way/435386992
 https://www.openstreetmap.org/changeset/41203606 
https://www.openstreetmap.org/changeset/41239724
https://www.openstreetmap.org/changeset/41239792
https://www.openstreetmap.org/changeset/41239857
https://www.openstreetmap.org/changeset/41239894

**Comment by Yurasi** [comment] 2016-08-04 23:22
Thanks for the feedback team

> ### Wrong turn lanes

https://www.openstreetmap.org/way/435322356/history It isn't mistake
https://www.openstreetmap.org/way/435322355/history It isn't mistake
https://www.openstreetmap.org/changeset/41249351
https://www.openstreetmap.org/changeset/41249384
https://www.openstreetmap.org/changeset/41249404
https://www.openstreetmap.org/way/435386346/history It isn't mistake
https://www.openstreetmap.org/way/435385009/history It isn't mistake
https://www.openstreetmap.org/way/435340631/history It isn't mistake

**Comment by pratikyadav** [comment] 2016-08-08 09:36
Thanks :pray: 

> Line does not match the bing aerial imagery https://www.openstreetmap.org/way/150850618

:negative_squared_cross_mark: Based on history, this way was not added by me but shows up in my edits as I added a note by joining nearby way. The way looks  aligned with bing and mapbox imagery. The only problem I spotted was 2 highway-water intersecting ways which I fixed here https://www.openstreetmap.org/changeset/41319685

> Add name of road using New & Misaligned TIGER Roads (2015) https://www.openstreetmap.org/way/434312883

:white_check_mark: Done https://www.openstreetmap.org/changeset/41319768

> Add multipolygon https://www.openstreetmap.org/way/435091342

:negative_squared_cross_mark:  Highly doubt this is multipolygon. Per http://wiki.openstreetmap.org/wiki/Tag:sport%3Drunning looks like `sport=running` and `leisure=track` are the tag to be used here.

> Improve the aligning of the water https://www.openstreetmap.org/way/368435592

:white_check_mark:  https://www.openstreetmap.org/changeset/41319950

**Comment by oini** [comment] 2016-08-08 09:53
Thanks for the feedbacks!

> #### Untagged way
> https://www.openstreetmap.org/way/434315898

✅ http://www.openstreetmap.org/changeset/41319777

> #### Improve the aligning of the highway
> https://www.openstreetmap.org/way/6775551 - check around
> https://www.openstreetmap.org/way/434315939

❎ In response to this map-feedback -> https://github.com/mapbox/map-feedback/issues/39412, all I did here was split an existing road into 3 parts and delete the part that did not exists. All the roads here have been added via Tiger Import and thus none of them align with satellite imagery like most other parts in the US and would require a separate task to fix them. Also, while working on map-feedbacks, we concentrate on fixing just the issue reported by the user. Nonetheless, I have aligned the 2 roads with the imagery:
- http://www.openstreetmap.org/changeset/41319966
- http://www.openstreetmap.org/changeset/41319921

**Comment by jothirnadh** [comment] 2016-08-08 12:51
Thanks for the review @karitotp 

#### Give form to the road : 
https://www.openstreetmap.org/changeset/41317219
https://www.openstreetmap.org/way/411851480/history
https://www.openstreetmap.org/way/411852188#map=18/30.85086/29.28713
Decided not to fix ^^ errors because this data is added by Facebook and they are going to revert their changes.

### Add layer=1
https://www.openstreetmap.org/way/435093463/history

**Comment by luiswalter** [comment] 2016-08-08 15:52
thanks Team!
#### `oneway=-1` is not recommended
https://www.openstreetmap.org/way/435358376#map=19/42.00944/-87.89394
https://www.openstreetmap.org/way/435345689#map=19/42.07960/-87.76118
https://www.openstreetmap.org/way/382386717#map=19/42.07955/-87.75570 No error
https://www.openstreetmap.org/way/109699060#map=19/42.03349/-87.75139
https://www.openstreetmap.org/way/435336150#map=19/42.03349/-87.74758
https://www.openstreetmap.org/way/435336165#map=19/42.03353/-87.75474
https://www.openstreetmap.org/way/435336205#map=19/42.03359/-87.75722
https://www.openstreetmap.org/way/435331876#map=19/42.06248/-87.74814
https://www.openstreetmap.org/way/435331864#map=19/42.06251/-87.75463
https://www.openstreetmap.org/way/435331868#map=19/42.06253/-87.75292
https://www.openstreetmap.org/way/435331872#map=19/42.06243/-87.74934
https://www.openstreetmap.org/way/435331870#map=19/42.06245/-87.75164
https://www.openstreetmap.org/way/435385338#map=19/42.05081/-87.68179
https://www.openstreetmap.org/way/313309913#map=19/42.04084/-87.74785

#### Incorrect number of turn lanes
https://www.openstreetmap.org/way/435328866#map=19/41.88805/-87.86346 No error
https://www.openstreetmap.org/way/435327212#map=19/41.90418/-87.93986
https://www.openstreetmap.org/way/435346227 No error

#### Wrong turn lanes
https://www.openstreetmap.org/way/435327231#map=19/41.91315/-87.93977 No error
https://www.openstreetmap.org/way/435327812#map=19/41.91721/-87.94024 no error
https://www.openstreetmap.org/way/435394498#map=19/42.13838/-87.85773

#### You need to add signaling of turn lane
https://www.openstreetmap.org/way/435327225 No error

#### The image doesn't show signal turn lane in all way
https://www.openstreetmap.org/way/435336188

**Comment by nikhilprabhakar** [comment] 2016-08-09 06:19
### Thanks a lot for the review and feedback team, below are my fixes and comments:

#### Fixes:

- Way untagged

https://www.openstreetmap.org/way/435022637 - [Fix](https://www.openstreetmap.org/changeset/41338191)

#### Comments:

- Remove turn lanes  unnecessary

https://www.openstreetmap.org/way/312343576 - No fix needed as this is a legitimate way of tagging turn lanes.
https://www.openstreetmap.org/way/312343574 - No fix needed as this is a legitimate way of tagging turn lanes.

**Comment by maanyaumashaanker** [comment] 2016-08-09 09:24
Thank you very much for reviewing the edits

#### Missing turn lanes
https://www.openstreetmap.org/changeset/41340044
https://www.openstreetmap.org/changeset/41340200
https://www.openstreetmap.org/changeset/41340276
In the other edits the data seems to be present.

#### Incorrect starting of turn lanes
https://www.openstreetmap.org/changeset/41340397
https://www.openstreetmap.org/changeset/41340496

#### Incorrect number of lanes
https://www.openstreetmap.org/way/435091072 in forward (looks right)
https://www.openstreetmap.org/changeset/41340881

**Comment by maning** [comment] 2016-08-10 08:27
Thanks! Here are my changes.

> Improve this building, incorrect shape: https://www.openstreetmap.org/way/429199900/history https://www.openstreetmap.org/way/427288208/history https://www.openstreetmap.org/way/317462859/history https://www.openstreetmap.org/way/426857623/history https://www.openstreetmap.org/way/427147375/history https://www.openstreetmap.org/way/429204953/history https://www.openstreetmap.org/way/429382330/history https://www.openstreetmap.org/way/429569036/history

https://www.openstreetmap.org/changeset/41362158


> Crossing buildings: https://www.openstreetmap.org/way/121783265/history

Won't fix, this is a building part and needs local to confirm.


> Orthogonalize this building: https://www.openstreetmap.org/way/429332718/history https://www.openstreetmap.org/way/427275212/history

https://www.openstreetmap.org/changeset/41362196

**Comment by krishnanammala** [comment] 2016-08-10 08:29
Thanks everyone for fixing the issues. Closing here.

**Closed by krishnanammala** 2016-08-10 08:29 UTC
Labels: peer-review
