### ISSUE TITLE
Import/validate LA Building import

### ISSUE THREAD

**Issue by maning** [mapbox/mapping#170] opened 2016-04-12 11:59 UTC
![LA building](https://c2.staticflickr.com/2/1665/26274562712_4cc1901d15.jpg)

_[LA City in osmbuildings.org](http://osmbuildings.org/?lat=34.02022&lon=-118.28057&zoom=15&rotation=30&tilt=45)_
### Objective

Validate and improve the imported buildings in Los Angeles.
### Background

The LA mapping community has started importing building footprints from high quality [open data](https://wiki.openstreetmap.org/wiki/Los_angeles,_California/Buildings_Import). 

This is a community managed import.  The whole data was divided into smaller chunks and loaded into a custom Tasking Manager which volunteer mapeers will manually check before import.  Sections of the city were sudvivided into several
TM projects.

Some parts of LA have existing building traced from satellite imagery, we need to ensure that the current import will  improve existing building data.  
### **Mapping Workflow**
- Please read the **[Importing guide](https://github.com/osmlab/labuildings/blob/master/IMPORTING.md)** provided by the LA import team.
- Go to the tasking manager at: **[http://labuildingsimport.com/](http://labuildingsimport.com/)**
- Select a completed task (marked as **Done**).
- Open JOSM.
- Load Bing Imagery, from the **Imagery** menu, select **Bing aerial imagery**.  The imagery from Bing was mostly from Los Angeles Region Image Acquisition Consortium (LARIAC).  This is the same imagery used as a reference for tracing the imported data.   In some areas the imagery is more updated than the imported data.
- Use the coloured buildings paint style. From the **View** menu, **Map paint styles** > **Map paint preferences**.  Select **Coloured buildings.de**.  This paint style will display buildings in different colors according to the `building` value.
- Add a filter to display only imported buildings: `lacounty building`
- Load the data in JOSM.  In the tasking manager, click **Edit with JOSM**.  This will download the data and a new background layer showing the polygon boundaries of the task.

![screen shot 2016-04-12 at 17 24 40](https://cloud.githubusercontent.com/assets/353700/14459079/77437cb2-00d3-11e6-8a58-3cd238d04d7e.png) 
- Run the JOSM Validator to fix common data errors. In the **Validation Results** panel, click **Validation**
- Visually scan the whole area for any data problems.
- Scan the whole area for any errors by referring to the imagery.
- Things to watch out (link to steps):
  - Some building maybe splitted into smaller parts, merged them to the larger part ([steps](https://github.com/osmlab/labuildings/blob/master/IMPORTING.md#validate-the-import-with-your-eyes-before-uploading)).  Use the [auto-tools plugin](https://github.com/Rub21/auto-tools).
  - Imported data may overlap with other building previously traced by other mappers. Check the geometry and tags of the data.  **Do not assume the imported data is better.** Conflate both buildings and choose the better geometry and tags ([steps](https://github.com/osmlab/labuildings/blob/master/IMPORTING.md#conflating-with-existing-data)).
  - New buildings maybe visible in the imagery, traced them ([steps](https://github.com/osmlab/labuildings/blob/master/IMPORTING.md#identifying-new-buildings-with-imported-and-existing-data)).  Likewise, buildings maybe demolished and does not exist anymore, delete them.
- Upload your changes with the following changeset comment: `[specific changes you made, i.e. Added new buildings, deleted non-existing buildings, fixed splitted buildings, removed duplicated nodes, etc.]Validating LA County Building Import #labuildings https://wiki.openstreetmap.org/wiki/Los_angeles,_California/Buildings_Import` and source: `Bing; JOSM Validator`.
### TM Projects to validate
- [x] **[Southside LA](http://labuildingsimport.com/project/2)**
- [x] **[Westside LA](http://labuildingsimport.com/project/3)**
- [x] **[Central and Eastside](http://labuildingsimport.com/project/6)**
- [x] **[SF Valley](http://labuildingsimport.com/project/7)**
- [x] **[Santa Monica & other random blocks](http://labuildingsimport.com/project/11)**
- [x] **[South Bay](http://labuildingsimport.com/project/10)**
- [x] **[Long Beach & Catalina Island](http://labuildingsimport.com/project/9)**
- [ ] **[Southeast](http://labuildingsimport.com/project/20)**
- [x] **[Malibu & Santa Monica Mountains](http://labuildingsimport.com/project/13)**
- [x] **[Pomona Valley](http://labuildingsimport.com/project/19)**
- [x] **[San Gabriel](http://labuildingsimport.com/project/17)**
- [x] **[Verdugos](http://labuildingsimport.com/project/22)**
- [ ] **[Antelope](http://labuildingsimport.com/project/18)**
- [ ] **[Northwest](http://labuildingsimport.com/project/15)**
- [x] **[Angeles forest](http://labuildingsimport.com/project/16)**

**Comment by maning** [comment] 2016-04-20 12:50
Per chat with LABuildings Import Team, let's work on finishing the first pass (import buildings) for **[Southside LA](http://labuildingsimport.com/project/2)**.  After the import we will work on validation.

Detailed steps is in the **[Importing Guide](https://github.com/osmlab/labuildings/blob/master/IMPORTING.md)**.

**Comment by maning** [comment] 2016-04-21 04:56
Southside project done!

![screen shot 2016-04-21 at 10 24 28](https://cloud.githubusercontent.com/assets/353700/14698322/4af03928-07ab-11e6-9ef6-f0a77049ec15.png)

Great work team :facepunch:  + :facepunch:  community! :boom: 

Lets continue validation.

**Comment by Andygol** [comment] 2016-04-22 12:42
For validation purpose you are able add JOSM style to highlight [features created in 2016]( https://raw.githubusercontent.com/Andygol/josm-styles/master/recent%20changes_2016.mapcss) or [created in 2015](https://raw.githubusercontent.com/Andygol/josm-styles/master/recent%20changes_2015.mapcss)

[Highlight data freshness](https://github.com/mapbox/mapping/wiki/Mapping%20with%20JOSM#highlight-data-freshness) - Mapbox mapping guide

![](https://cloud.githubusercontent.com/assets/369696/9634340/e596f890-5199-11e5-8335-55d63a9b11d2.gif)

**Comment by maning** [comment] 2016-04-22 14:35
![f4](https://cloud.githubusercontent.com/assets/353700/14743042/08bc89b8-08bd-11e6-9098-075db6049701.gif)<br>*Wildasin area LA in [F4map](http://demo.f4map.com/#lat=33.9663534&lon=-118.3026612&zoom=18&camera.theta=66.077&camera.phi=-0.333)*

Great work this week team!

As of today, we've imported **~294K** :house: from **67** different users ( 👪 ).
Data team will continue to validate :mag: [Southside](http://labuildingsimport.com/project/2) while LA community will start working on [the Westside](http://labuildingsimport.com/project/3).  MaptimeLA is also lining up another mapathon :pizza: .

Reminders when validating,  **always checkout the [What to watch out for](https://github.com/osmlab/labuildings/blob/master/IMPORTING.md#what-to-watch-out-for) section of the Importing guide.**

Here are resources you can use to monitor progress:
* Taginfo count of all buildings imported (updated daily) - https://taginfo.openstreetmap.org/keys/lacounty:bld_id
* Monitor changeset comments around LA - https://www.mapbox.com/osm-comments/#/changesets/?q=bbox:-119.0533,33.7038,-117.7721,34.3378%20users:*%20from:2016-04-01&show=all
* Chatroom for the import team - https://gitter.im/osmlab/labuildings
* Post issues/tickets here - https://github.com/osmlab/labuildings

**Comment by maning** [comment] 2016-05-03 03:39
Updated the OP to include auto-tools plugin.

**Comment by maning** [comment] 2016-06-22 03:42
![screen shot 2016-06-21 at 21 09 54](https://cloud.githubusercontent.com/assets/353700/16253904/5afe1bea-3858-11e6-95bb-71992cf9303a.png)

👏 work on validating **[Westside LA](http://labuildingsimport.com/project/3)**

As of today, we've imported **527 823** :house: 🏡 🏢 🏨 🏬 🏭  participated by **99** different users ( 👪 ).
MaptimeLA is also lining up another mapathon :pizza: (June 25) we will import and validate [Central and Eastside](http://labuildingsimport.com/project/6) after the mapathon.

**Comment by maning** [comment] 2016-07-01 04:54
![](https://cloud.githubusercontent.com/assets/5607844/16506672/f747326c-3ef1-11e6-82cf-ba15672fdbf2.jpg)

Nice work everyone!  Let's move to [Central and Eastside](http://labuildingsimport.com/project/6)

We are also lining up diaries related to this import. Post on tools is up: http://www.openstreetmap.org/user/manings/diary/38969

**Comment by maning** [comment] 2016-07-03 12:08
When importing/validating, the changeset source tag default's to the census block TM endpoint.  This is [usual behavior of the Tasking Manager](https://github.com/hotosm/osm-tasking-manager2/issues/766).  

![](https://files.gitter.im/osmlab/labuildings/rtoc/Screen_Shot_2016-07-03_at_12_52_09_AM.png)

Please make sure to replace the source tag to the suggested tag: 

* During import: `LA County GIS, http://egis3.lacounty.gov/dataportal/`
* During validation: `Bing; JOSM Validator`

**Comment by Rub21** [comment] 2016-07-04 15:28
> Please make sure you replace the source to the suggested tag:
> During import: LA County GIS, http://egis3.lacounty.gov/dataportal/


@maning  I think it is easy if we change the `imagery` in  the task manager: 
replace  `tms[22]:https://api.mapbox.com/v4/maning.2aa1b116/{zoom}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFuaW5nIiwiYSI6IlhjWGNfdTQifQ.ras0nImWG638BCDSxU8bqw` by    `LA County GIS, http://egis3.lacounty.gov/dataportal/`


![screenshot from 2016-07-04 10 26 53](https://cloud.githubusercontent.com/assets/1152236/16565296/fa08219a-41d1-11e6-85f8-e6c250c1bd7c.png)

> During validation: Bing; JOSM Validator

For validations also we can change it, but maybe it will become quite complicate.

**Comment by maning** [comment] 2016-07-04 16:17
@Rub21 The TMS url appear in the source because we are using that layer as a reference for the census blocks boundaries.  It was discussed already in the TM GH repo and there is no consensus how to move forward.  For now, let's just manually add the source.  If you used it before, it should be in the dropdown list of the JOSM changeset source before upload.

![screen shot 2016-07-04 at 21 46 00](https://cloud.githubusercontent.com/assets/353700/16566305/daee26ce-4230-11e6-8741-25b9bc1aafa1.png)

**Comment by maning** [comment] 2016-07-12 06:06
**On rural areas of LA, Bing maybe updated.**  LA County gave us permission to use their 2014 LARIAC imagery.  Use LARIAC 2014 along with Bing to verify if the buildings exist or not.

Details on how to load the TMS in JOSM here: https://github.com/osmlab/labuildings/blob/master/IMPORTING.md#add-la-county-imagery-for-rural-areas

**Comment by maning** [comment] 2016-07-26 11:11
![](https://cloud.githubusercontent.com/assets/353700/16916917/fa073ec8-4d1c-11e6-90b8-6b602253fa2f.gif)

Awesome work @mapbox/team-data!  Let's continue validating the 2 projects this week.

**Comment by samely** [comment] 2016-07-26 14:19
Wow!!! Looks amazing :rocket:

**Comment by maning** [comment] 2016-08-03 03:45
We did this!  Great work everyone!

![screen shot 2016-08-03 at 09 08 42](https://cloud.githubusercontent.com/assets/353700/17353092/15f153fa-595a-11e6-8017-94088ce1b594.png)
![screen shot 2016-08-03 at 09 08 31](https://cloud.githubusercontent.com/assets/353700/17353091/15923974-595a-11e6-9fe9-c61d202b42ec.png)

We will do a round of cleanup sweep (tracked [here](https://github.com/osmlab/labuildings/issues?q=is%3Aissue+is%3Aopen+label%3Acleanup).  

@mapbox/team-data, please share here your pain points during the validation process.  Your insights will help us improve the process for the next phase of import.

**Comment by geohacker** [comment] 2016-08-03 04:00
![](https://media.giphy.com/media/MTclfCr4tVgis/giphy.gif)

**Comment by maning** [comment] 2016-09-17 09:09
Reopening for phase 2.  OP is updated for the latest TM projects.

**Comment by maning** [comment] 2016-11-04 01:21
@mapbox/team-data Lets finish  **[Southeast](http://labuildingsimport.com/project/20)**.  After that, a [new data will be processed based on the latest release by LA County](https://github.com/osmlab/labuildings/issues/111).  Will update OP for new projects as soon as we process the data.

**Comment by maning** [comment] 2016-12-10 13:53
New data processed and ready for import.

**Comment by abhisheksaikia** [comment] 2017-01-30 07:27
@mapbox/team-data  Let us restart LA building imports starting today. We will first complete [Pomona Valley](http://labuildingsimport.com/project/19) and then move to the other open tasks: [San Gabriel](http://labuildingsimport.com/project/17) and [Verdugos](http://labuildingsimport.com/project/14).

**Note**: Let's concentrate on import first and we can get back to validation afterwards.

**Next actions:**

* [ ] @maning to keep on opening newer tasks as the tasks are completed.
* [ ] @krishnanammala and me to coordinate across AYP and BLR to hit out the tasks this week.
* [ ] @krishnanammala and me to update/track daily stats in MapTrac.

**Comment by abhisheksaikia** [comment] 2017-02-02 12:44
@mapbox/team-data While doing LA building imports we have come across some common errors from the mappers:

1. Duplicate Buildings (220)
2. Self intersecting ways (20)
3. Crossing/overlapping buildings (1314)

This figures are based on yesterday's edits by the data team at Mapbox and account for a mere 0.8 % error out of the 175000 buildings we uploaded yesterday. So while the problem is very small, it is still desirable to solve it at the mapper's end as much as possible rather than leave it for validation.

### Why this is happening and how to solve these issues?

**Duplicate buildings**: A total of 202 exact duplicates. This happens when mappers work on adjacent blocks and are uploading at the same time. Due to the nature of chunks in the task, some buildings lie on both the adjacent tasks and are ended up being uploaded by both the mappers causing duplicates. If and when it comes up as an error during validation, **one can simply use `fix` to fix these errors**. 

**Self intersecting ways**: 14 self intersecting ways. Cannot be fixed on the mapper end. This is due to a problem in JOSM when the validator does not detect self intersecting ways due to topology unless there is an intersection node.

**Overlapping/crossing buildings**: A total of 1314 overlapping buildings have been detected from yesterday's edits but not detected by JOSM validator. Now, this happens due to a quirk in JOSM validator. Possible reason: JOSM validator validates only data which is previously present in OSM and not any new data which has not been uploaded. Meaning, once a mapper loads both the data layer and the import layer and merges them, run the validator, the validator will only identify overlapping/crossing buildings if they are already present in OSM and not on the new import buildings. So, when an import building overlaps with a previously existing building, the validator will not show it up as an error. 

While not the most elegant solution, this is what we can do to avoid the errors:

**Upload data and import layer to JOSM> run validator in import layer > fix any errors > merge both the layers > run validator again on the merged layer > fix errors > press upload button and cancel > fix any more new issues that crop up > finally upload**

Once you press upload and then cancel, the validator this time runs through the entire dataset (old and new) and give any errors. 

Again, not the best solution but helps to get rid of these overlapping/crossing building errors.

![validator](https://cloud.githubusercontent.com/assets/13744156/22549841/5eb6f28a-e973-11e6-9bf8-91a3fa96955e.gif)



**An example of validator fail**

**Comment by dannykath** [comment] 2017-02-02 14:46
@abhisheksaikia 
I think  you  are doing something wrong about validation, if you just select a building, obviously it will not give you an error, so you have to all the buildings and you will see all errors .

**Comment by abhisheksaikia** [comment] 2017-02-02 17:04
@dannykath Thanks for the heads up. Will post a more appropriate GIF to demonstrate an exmaple of validator failing. Edited the comment and removed the GIF ^

**Comment by krishnanammala** [comment] 2017-02-03 12:19
We came across [some common errors](https://github.com/mapbox/mapping/issues/170#issuecomment-276947822) while doing LA Building import like:

* Duplicate buildings
* Self intersecting ways
* Crossing/Overlapping buildings

Most of the team members faced the issue in `JOSM Validator ` not displaying the errors in the above cases for buildings. We tried comparing with different versions of JOSM & JAVA and figured out that the problem is in the user data preferences.

To remove the user data in your JOSM preferences:

* [For Mac](https://josm.openstreetmap.de/wiki/Help/Preferences#MacOSX) , run the command `rm -r ~/Library/JOSM/ ` in your home directory.

* [For Linux](https://josm.openstreetmap.de/wiki/Help/Preferences#Linux) , run the command `rm -r ~/.local/share/JOSM` in your home directory

**Note**: Make sure to close your JOSM , while running the command in your terminal.

After running this, JOSM is able to detect the errors 💥 

cc @abhisheksaikia @maning

**Comment by Rub21** [comment] 2017-02-03 14:38
@krishnanammala @maning 
> Duplicate buildings
> Self intersecting ways
> Crossing/Overlapping buildings


These issues could be detected by osmlint!!

**Comment by geohacker** [comment] 2017-02-06 07:28
>  To remove the user data in your JOSM preferences:

> For Mac , run the command rm -r ~/Library/JOSM/ in your home directory.

> For Linux , run the command rm -r ~/.local/share/JOSM in your home directory

@mapbox/team-data - Do not clear your JOSM home directory unless you want to entirely wipe your JOSM preferences and start a fresh install. rm -r is in general a bad practice - you'd have to install all your plugins and configure them afterwards. 

## To solve the validator not showing all errors:

* Make sure you uncheck 'Use ignore list'
* Check 'Show information level'
* Check 'Show information level on upload.'

![](https://www.evernote.com/l/AR_iKpQh1lZNy4caEJLXaDtFAPZDw-svxREB/image.png)

**Comment by abhisheksaikia** [comment] 2017-02-06 07:57
@mapbox/team-data Great work on hitting out [San Gabriel](http://labuildingsimport.com/project/17) , [Verdugos](http://labuildingsimport.com/project/22) and [Pomona Valley](http://labuildingsimport.com/project/19) tasks last week. We imported a total of ~ **587932** buildings in LA with ~20 mappers working on it across 5 days 🎉 .

Let us continue the great work this week and hit out the remaining tasks:
[Northwest - LABuildings Import](http://labuildingsimport.com/project/15)
[Antelope - LABuildings Import](http://labuildingsimport.com/project/18)
[Angeles forest - LABuildings Import](http://labuildingsimport.com/project/16)

**Comment by maning** [comment] 2017-02-08 12:44
**Import complete! 2.9M buildings added.  Let's continue with validation.**

**Comment by bsrinivasa** [comment] 2017-02-10 03:09
The Map Paint Style - **Coloured Buildings.de** was modified and the the German descriptions were translated to English language. Find **[Coloured Buildings.en](https://gist.github.com/bsrinivasa/b74e0d95b7f144c8f9f0aa17f65274c3#file-coloured-buildings-en-mapcss)**  style in the gist. This could be loaded as a custom Map Paint Style in JOSM. 

![image](https://cloud.githubusercontent.com/assets/17143802/22811082/bb0b90aa-ef62-11e6-91db-d6e6249ab835.png)

**Comment by maning** [comment] 2017-02-13 08:51
![screen shot 2017-02-13 at 14 18 11](https://cloud.githubusercontent.com/assets/353700/22876553/4f1b055a-f1f7-11e6-8d8b-ab9a42d66bd7.png)
*Mainland LA County*

Final numbers

* ~2.92 M buildings
* ~300 usernames/mappers

**Closed** 2017-02-13 08:51 UTC
Labels: Master, Validation
