### ISSUE TITLE
Japan realignment and add roads

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#116] opened 2015-09-01 18:23 UTC
**Task** http://tasks.openstreetmap.in/project/31#

Realign and add new residential and main roads.

**Task coverage**
- Chiba Prefecture, Japan

**Tracing Sources**
- Japan GSI Orthorectified Satellite: `http://cyberjapandata.gsi.go.jp/xyz/ort/{z}/{x}/{y}.jpg` 
- Bing (offset)
- Mapbox Satellite (offset)

**Reference Sources**
- Strava Globalheat: `http://globalheat.strava.com/tiles/both/color3/{zoom}/{x}/{y}.png`
- OSM GPS : `http://{switch:a,b,c}.gps-tile.openstreetmap.org/lines/{z}/{x}/{y}.png`
- Japan GSI Map 2012 `http://cyberjapandata.gsi.go.jp/xyz/std2012/{z}/{x}/{y}.png`

**Timeline**
- @mapbox/team-data  will work since Tuesday 1st of September at 13:30 hours. Team training was done and expected completion is about a week.
- team-blr are on the task full time from 09/04

**Instructions**
- Align and add roads verifiable from satellite imagery
- If editing in a actively mapped area, add a note instead of making a fix. **Don't assume anything**.
- If using [`Japan Layer`](http://wiki.openstreetmap.org/wiki/GSImaps) to add or align, tag the road with `source=GSImaps/TileID`.

**Tips and tricks**
- Lower the opacity of the `Japan Layer` to 30% or 20% to align with Bing and GPS layers.
- You can select a road and align it with *Improve way accuracy mode (w)*. Also you can add nodes with *Ctrl*.
![image](https://cloud.githubusercontent.com/assets/10425629/9612686/a63da4f2-50ac-11e5-96ed-b5fe3850818f.png)
- You can add filters `boundary: | leisure: | landuse: | waterway: | sport:  |amenity: | natural:|building: |  admin_level:  | power: | place: |  type:relation  | electrified :| railway:| aeroway:`

cc. @mapbox/team-data @lxbarth @aaronlidman

**Comment by pratikyadav** [comment] 2015-09-03 13:08
As per voice with @planemad , the `Japan Layer` is not that accurate. Thus, the primary source for mapping should be Bing/Mapbox Satellite imagery followed by Strava and GPS layer.

![japan](https://cloud.githubusercontent.com/assets/12744420/9658820/e7e9fbd0-5269-11e5-8ee1-3a50cc229f87.gif)

**Comment by pratikyadav** [comment] 2015-09-03 13:34
As per voice with @planemad , the `Japan Layer` seems to be accurate for major roads but not for minor roads. Thus, for minor roads the primary source of mapping should be Bing/Mapbox-satellite.

![japan](https://cloud.githubusercontent.com/assets/12744420/9659425/10c239a6-526e-11e5-9e44-0ff50f9c9dd8.gif)

**Comment by planemad** [comment] 2015-09-03 14:23
@Rub21 we are noticing the above inconsistency in road quality in the Japan layer for minor roads. The problem is not a simple offset, but it does not match the road geometry. There is not much use tracing unclassified or residential roads from it as they will need to be realigned again.

Can you look carefully into this problem and see what is the best way to proceed? Maybe we should only realign roads from tertiary and up in the first pass using the Japan layer.

**Comment by almccon** [comment] 2015-09-03 20:38
It looks like your tasks.openstreetmap.in tasking server has the wrong hashtag assigned to these changesets. It's applying #hotosm-project-31 to the changesets, for example this one: https://www.openstreetmap.org/changeset/33760039

This is not a HOT project, correct? It's project 31 on tasks.openstreetmap.in, but not on http://tasks.hotosm.org/. So the default hashtag needs to be changed.

Thanks for your work! Can I ask what is the context for this Japan mapping task? I'm working on an OSM style for Japan for another project, so I'm curious!

**Comment by aaronlidman** [comment] 2015-09-03 21:36
Hey @almccon, thanks for the heads up @ediyes fixed the changeset comments.

For context, we've had our eye on fixing Japan for a while. We did a trial run of fixing the well known connectivity issues last November when the team was much smaller and decided to punt for the time being. Before getting to the connectivity issues again we're taking a first pass at alignment issues, which surprised us. Afterwards we'll focus on connectivity, using debugging tools from OSRM to tell us where to fix.

![02a30fca-7007-11e4-8dff-dd8a4528cad5 1](https://cloud.githubusercontent.com/assets/58878/9671123/9769f756-525e-11e5-8bca-637bfa88a6cc.png)
*Connectivity issues in Tokyo a team of four fixed from Nov 14th - 18th*

**Comment by almccon** [comment] 2015-09-03 21:52
Great news! Thanks for the improvement!

**Comment by aarthykc** [comment] 2015-09-04 06:57
This could be a possible workflow to realign existing roads or trace new roads: 

- Using the Strava layer align the data layer and the satellite imagery by using the Imagery Offset setting  in Imagery, like this: 

![offset setting](https://cloud.githubusercontent.com/assets/10141319/9678124/5df95fa6-52ff-11e5-893f-5124abcdeacb.gif)
Now that you've done that you can be sure of the fact that your imagery is correct.

- After this you can proceed to trace new roads with respect to the imagery. Try as much as possible to NOT use the Japan Layer as a reference as in many places it's incorrect. Like here:
![screen shot 2015-09-04 at 11 53 30 am](https://cloud.githubusercontent.com/assets/10141319/9678212/1d27912c-5300-11e5-9629-183d566661a2.png)

**Comment by aarthykc** [comment] 2015-09-04 09:04
Case where the road needs to be realigned: 
![screen shot 2015-09-04 at 2 31 22 pm](https://cloud.githubusercontent.com/assets/10141319/9680104/02624708-5312-11e5-85f5-b0f944405309.png)

**Comment by planemad** [comment] 2015-09-04 09:29
Building on @pratikyadav's and @aarthykc's observations, it does not look worthwhile to use the `Japan GSI` layer directly for tracing new roads as it creates more misaligned data. We need to get our sources in order before tracing.

**Step 1: Align the satellite imagery**
- Use the `Strava Globalheat` layer as the gps reference, if data is not available try using `Runkeeper` or `OSM GPS`. This is the only dependable reference data collected from the ground.
- Create a new offset for the `Bing` or `Mapbox Satellite` imagery and align it to match the gps reference. This is best done at a road junction where the offset can be corrected on both axis.
- Verify the offset is accurate by checking the reference and satellite imagery in other junction in the mapping area
![untitled](https://cloud.githubusercontent.com/assets/126868/9680155/6e59cfbc-5312-11e5-9d52-71c8dc9aa7a3.gif)

**Step 2: Align the Japan GSI layer**
- Use the same technique to offset the GSI layer to match the major highways with the gps layer.
- The GSI layer has both offset and geometry distortion from the reality and will not align perfectly with either the data, satellite or gps layer. Minor roads are more distorted and have lower accuracy than highways.
![untitled](https://cloud.githubusercontent.com/assets/126868/9680612/8e0d7d42-5315-11e5-8bfc-b261b0d83f70.gif)

**Step 3: Realign existing highways and add new roads
- The priority for sources are: gps layer > satellite imagery > Japan GSI layer

**Comment by Andygol** [comment] 2015-09-04 10:38
* Can we use layer with satellite images `http://cyberjapandata.gsi.go.jp/xyz/ort/{z}/{x}/{y}.jpg` `source=GSImaps/ort` instead of layer `http://cyberjapandata.gsi.go.jp/xyz/std2012/{z}/{x}/{y}.png`  ?
(see. http://wiki.openstreetmap.org/wiki/GSImaps#Ortho_Photo_Tiles)

* It would be great if we'll use **Imagery Offset Database** - http://wiki.openstreetmap.org/wiki/Imagery_Offset_Database for sharing offsets for particular layer

**Comment by planemad** [comment] 2015-09-04 11:00
Comparison of GPS corrected OSM data vs Japan GSI layer:
- For this small town the difference was in the range of 4-16m
![screen shot 2015-09-04 at 4 26 42 pm](https://cloud.githubusercontent.com/assets/126868/9682181/dc6b4526-5321-11e5-8a46-cf6c01dd5403.png)

**Comment by planemad** [comment] 2015-09-04 11:05
@Andygol Amazing find. The GSI orthorectified imagery matches the GPS data perfectly. It is the GSI maps that are inaccurate.
![screen shot 2015-09-04 at 4 33 57 pm](https://cloud.githubusercontent.com/assets/126868/9682282/dccb1d38-5322-11e5-97c4-ab57ba45cf5e.png)

Going to update the instructions.

**Comment by mapconcierge** [comment] 2015-09-15 09:23
Hi, all:

About Reference data,
We should use below GSImaps layers

std(maximum zoom level: 18)
http://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png

ort(maximum zoom level: 18)
http://cyberjapandata.gsi.go.jp/xyz/ort/{z}/{x}/{y}.png

Both ort and std should not have offset, as you know wink emoticon

**Comment by planemad** [comment] 2015-09-15 11:19
@mapconcierge 

From our trials, the `ort` imagery is very good and [matches the Strava](https://github.com/mapbox/mapping/issues/116#issuecomment-137705381) GPS traces. But the coverage of the imagery over Japan is not complete.

The `std` maps are accurate for major highways (motorway - secondary) [but are not reliable for smaller roads and rural areas](https://github.com/mapbox/mapping/issues/116#issuecomment-137704758) where the accuracy is poor. 

**Positional accuracy of data**
1. Strava Globalheat
2. GSI Japan Satellite (ort)
3. GSI Japan Map (std) [Only major highways and cities]
4. OSM GPS
5. Bing Satellite
6. OSM Data

**Comment by mapconcierge** [comment] 2015-09-17 04:19
Okay, I agree your priorities.

**Comment by mapconcierge** [comment] 2015-09-17 19:09
I made a task for Aomori area on TeachOSM.
http://tasks.teachosm.org/project/78

**Comment by planemad** [comment] 2015-09-29 06:19
Tracking on #120

**Closed by planemad** 2015-09-29 06:19 UTC
